extends "res://tests/playthrough.gd"
## Rewrites scripts/case_starts.gd, the state the title screen's case jumps start from, by running the full playthrough
## and snapshotting the flags and inventory as each "Case N" card comes up. Every case is fully solved by then, with
## every clue and board seed, so the best ending stays reachable. Re-run it when a case gains clues or flags:
##
## Godot_v4.7_console.exe --headless --path . res://tests/capture_case_starts.tscn

const OUT := "res://scripts/case_starts.gd"

var _starts := {}


func _process(delta: float) -> void:
	super._process(delta)
	if _failed or main == null:
		return
	for done in range(1, 5):
		var n := done + 1
		# caseN_done is set just before the card, and nothing else changes until the card is clicked
		if Game.flag("case%d_done" % done) and not Game.flag("case%d_started" % n) and not _starts.has(n):
			_starts[n] = {"flags": Game.flags.duplicate(true), "inventory": Game.inventory.duplicate()}
			print("captured the start of Case %d" % n)
			_check(n)
			if n == 5:
				_write()


func _check(n: int) -> void:
	## Every clue of the earlier cases should be in the notebook.
	for id: String in Game.CLUES:
		if int(Game.CLUES[id][0]) < n and not Game.flag(id):
			_fail("Case %d starts without %s" % [n, id])


func _write() -> void:
	if _failed:
		return
	var src := "## Generated by tests/capture_case_starts.tscn: don't edit by hand, re-run it.\n" \
			+ "## The flags and inventory a full playthrough has when each case's card comes up (Main.jump_to_case).\n\n" \
			+ "const STARTS := {\n"
	for n in [2, 3, 4, 5]:
		var flags: Dictionary = _starts[n]["flags"]
		var keys := flags.keys()
		keys.sort()
		src += "\t%d: {\n\t\t\"inventory\": %s,\n\t\t\"flags\": {\n" % [n, JSON.stringify(_starts[n]["inventory"])]
		for k in keys:
			src += "\t\t\t%s: %s,\n" % [JSON.stringify(k), JSON.stringify(flags[k])]
		src += "\t\t},\n\t},\n"
	src += "}\n"
	var f := FileAccess.open(OUT, FileAccess.WRITE)
	f.store_string(src)
	f.close()
	print("CAPTURE OK - wrote ", OUT)
	_quit(0)
