# Generated by tools/r3/gen_sprites.py - row/frame layout of assets/characters/detective.png
# (detective_light.png has the same layout: R/G/B = shading from the left key, right key and back rim)
extends RefCounted

const FRAME_SIZE := Vector2i(240, 372)
const PIVOT := Vector2(120, 360)
const HEIGHT := 312.0

## name: [row, frame_count, fps, loop]
const ANIMS := {
	"idle_right": [0, 8, 6, true],
	"walk_right": [1, 12, 12, true],
	"idle_down": [2, 8, 6, true],
	"walk_down": [3, 12, 12, true],
	"idle_up": [4, 8, 6, true],
	"walk_up": [5, 12, 12, true],
	"talk_right": [6, 6, 8, true],
	"talk_down": [7, 6, 8, true],
	"pickup_right": [8, 7, 8, false],
	"use_right": [9, 5, 8, false],
	"notebook_right": [10, 9, 6, false],
	"look_around": [11, 8, 4, true],
	"shrug": [12, 6, 8, false],
	"show_badge": [13, 6, 6, false],
	"idle_left": [14, 8, 6, true],
	"walk_left": [15, 12, 12, true],
	"talk_left": [16, 6, 8, true],
	"pickup_left": [17, 7, 8, false],
	"use_left": [18, 5, 8, false],
	"notebook_left": [19, 9, 6, false],
}
